# Generated by Django 5.2.8 on 2026-03-22 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Group Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_entry_groups', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry_groups', to='organization.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Entry Group',
                'verbose_name_plural': 'Stock Entry Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('warehouse_to_warehouse', 'Warehouse to Warehouse'), ('warehouse_to_branch', 'Warehouse to Branch'), ('branch_to_branch', 'Branch to Branch'), ('branch_to_warehouse', 'Branch to Warehouse')], max_length=30, verbose_name='Transfer Type')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=None, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Purchase Price Per Unit')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Selling Price Per Unit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='organization.branch', verbose_name='Destination Branch')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='organization.warehouse', verbose_name='Destination Warehouse')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='products.product')),
                ('source_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='organization.branch', verbose_name='Source Branch')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='organization.warehouse', verbose_name='Source Warehouse')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='stock.supplier')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Purchase Price Per Unit')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price Per Unit')),
                ('reorder_level', models.IntegerField(default=0)),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Batch')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_initial_stock', models.BooleanField(default=True, help_text='True if this is initial stock added directly, False if from transfer', verbose_name='Is Initial Stock')),
                ('original_batch_number', models.CharField(blank=True, help_text='The original batch number before transfer', max_length=100, verbose_name='Original Batch Number')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('original_stock_entry', models.ForeignKey(blank=True, help_text='The original stock entry this was transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_entries', to='stock.stockentry', verbose_name='Original Stock Entry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='organization.warehouse')),
                ('entry_group', models.ForeignKey(blank=True, help_text='Group this entry belongs to (for multi-product entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='stock.stockentrygroup', verbose_name='Entry Group')),
                ('source_transfer', models.ForeignKey(blank=True, help_text='The transfer that created this stock entry (if from transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_stock_entries', to='stock.stocktransfer', verbose_name='Source Transfer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='stock.supplier')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Purchase Price Per Unit')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price Per Unit')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Reserved Quantity')),
                ('reorder_level', models.IntegerField(default=0)),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Batch')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_initial_stock', models.BooleanField(default=False, help_text='True if this is initial stock added directly, False if from transfer (branches only receive stock via transfers)', verbose_name='Is Initial Stock')),
                ('original_batch_number', models.CharField(blank=True, help_text='The original batch number before transfer', max_length=100, verbose_name='Original Batch Number')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='organization.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('original_branch_stock', models.ForeignKey(blank=True, help_text='The original branch stock entry this was transferred from (for branch-to-branch transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_entries', to='stock.branchstock', verbose_name='Original Branch Stock Entry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock_entries', to='products.product')),
                ('original_stock_entry', models.ForeignKey(blank=True, help_text='The original warehouse stock entry this was transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_branch', to='stock.stockentry', verbose_name='Original Warehouse Stock Entry')),
                ('source_transfer', models.ForeignKey(blank=True, help_text='The transfer that created this stock entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_branch_stock', to='stock.stocktransfer', verbose_name='Source Transfer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_stock_entries', to='stock.supplier')),
            ],
            options={
                'verbose_name': 'Branch Stock Entry',
                'verbose_name_plural': 'Branch Stock Entries',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal'), ('correction', 'Correction'), ('damaged', 'Damaged')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity Change')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price (if adding stock)')),
                ('reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_adjustment', models.ForeignKey(blank=True, help_text='The adjustment that was corrected by this adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_adjustments', to='stock.stockadjustment', verbose_name='Corrected Adjustment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='organization.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'created_at'], name='stock_stock_product_2abf22_idx'), models.Index(fields=['adjustment_type', 'created_at'], name='stock_stock_adjustm_a04852_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Purchase Price Per Unit')),
                ('reorder_level', models.IntegerField(blank=True, default=None, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Selling Price Per Unit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch Number')),
                ('notes', models.TextField(blank=True, verbose_name='Item Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='products.product', verbose_name='Product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stocktransfer', verbose_name='Transfer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items', to='stock.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Stock Transfer Item',
                'verbose_name_plural': 'Stock Transfer Items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['transfer', 'product'], name='stock_stock_transfe_a6e5c9_idx'), models.Index(fields=['product', 'transfer'], name='stock_stock_product_7ae489_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_type', 'status'], name='stock_stock_transfe_c48fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['product', 'status'], name='stock_stock_product_b8597e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['source_warehouse', 'status'], name='stock_stock_source__f878b8_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['source_branch', 'status'], name='stock_stock_source__5349b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination_warehouse', 'status'], name='stock_stock_destina_30b6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination_branch', 'status'], name='stock_stock_destina_f56f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status', 'created_at'], name='stock_stock_status_6675ab_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['product', 'warehouse'], name='stock_stock_product_79e55e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['warehouse', 'received_date'], name='stock_stock_warehou_85089f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['product', 'purchase_price'], name='stock_stock_product_bdf0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['product', 'branch'], name='stock_branc_product_36c741_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['branch', 'received_date'], name='stock_branc_branch__c8f808_idx'),
        ),
        migrations.AddIndex(
            model_name='branchstock',
            index=models.Index(fields=['product', 'purchase_price'], name='stock_branc_product_4960ef_idx'),
        ),
    ]
