# Generated by Django 5.2.8 on 2025-11-22 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal'), ('correction', 'Correction'), ('damaged', 'Damaged'), ('returned', 'Returned')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity Change')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price (if adding stock)')),
                ('reason', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='organization.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'created_at'], name='stock_stock_product_2abf22_idx'), models.Index(fields=['adjustment_type', 'created_at'], name='stock_stock_adjustm_a04852_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('warehouse_to_warehouse', 'Warehouse to Warehouse'), ('warehouse_to_branch', 'Warehouse to Branch'), ('branch_to_branch', 'Branch to Branch'), ('branch_to_warehouse', 'Branch to Warehouse')], max_length=30, verbose_name='Transfer Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Price Per Unit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='organization.branch', verbose_name='Destination Branch')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='organization.warehouse', verbose_name='Destination Warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='products.product')),
                ('source_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='organization.branch', verbose_name='Source Branch')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='organization.warehouse', verbose_name='Source Warehouse')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transfer_type', 'status'], name='stock_stock_transfe_c48fd8_idx'), models.Index(fields=['product', 'status'], name='stock_stock_product_b8597e_idx'), models.Index(fields=['source_warehouse', 'status'], name='stock_stock_source__f878b8_idx'), models.Index(fields=['source_branch', 'status'], name='stock_stock_source__5349b1_idx'), models.Index(fields=['destination_warehouse', 'status'], name='stock_stock_destina_30b6fa_idx'), models.Index(fields=['destination_branch', 'status'], name='stock_stock_destina_f56f9e_idx'), models.Index(fields=['status', 'created_at'], name='stock_stock_status_6675ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Price Per Unit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='organization.warehouse')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='stock.supplier')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-received_date', '-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse'], name='stock_stock_product_79e55e_idx'), models.Index(fields=['warehouse', 'received_date'], name='stock_stock_warehou_85089f_idx'), models.Index(fields=['product', 'purchase_price'], name='stock_stock_product_bdf0ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Price Per Unit')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price Per Unit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='organization.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branch_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock_entries', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_stock_entries', to='stock.supplier')),
            ],
            options={
                'verbose_name': 'Branch Stock Entry',
                'verbose_name_plural': 'Branch Stock Entries',
                'ordering': ['-received_date', '-created_at'],
                'indexes': [models.Index(fields=['product', 'branch'], name='stock_branc_product_36c741_idx'), models.Index(fields=['branch', 'received_date'], name='stock_branc_branch__c8f808_idx'), models.Index(fields=['product', 'purchase_price'], name='stock_branc_product_4960ef_idx')],
            },
        ),
    ]
