# Generated by Django 5.2.8 on 2025-11-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='batch_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='batch_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Reference Number'),
        ),
    ]
