# Generated by Django 5.2.8 on 2025-11-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_branchstock_reorder_level_stockentry_reorder_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchstock',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='reorder_level',
        ),
    ]
