# Generated by Django 5.2.8 on 2025-11-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_branchstock_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
    ]
