# Generated by Django 5.2.8 on 2025-11-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_branchstock_reorder_level_stockentry_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='stock.supplier'),
        ),
    ]
