# Generated by Django 5.2.8 on 2025-11-23 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stocktransfer_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='is_initial_stock',
            field=models.BooleanField(default=False, help_text='True if this is initial stock added directly, False if from transfer (branches only receive stock via transfers)', verbose_name='Is Initial Stock'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='original_batch_number',
            field=models.CharField(blank=True, help_text='The original batch number before transfer', max_length=100, verbose_name='Original Batch Number'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='original_branch_stock',
            field=models.ForeignKey(blank=True, help_text='The original branch stock entry this was transferred from (for branch-to-branch transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_entries', to='stock.branchstock', verbose_name='Original Branch Stock Entry'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='original_stock_entry',
            field=models.ForeignKey(blank=True, help_text='The original warehouse stock entry this was transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_branch', to='stock.stockentry', verbose_name='Original Warehouse Stock Entry'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='source_transfer',
            field=models.ForeignKey(blank=True, help_text='The transfer that created this stock entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_branch_stock', to='stock.stocktransfer', verbose_name='Source Transfer'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='is_initial_stock',
            field=models.BooleanField(default=True, help_text='True if this is initial stock added directly, False if from transfer', verbose_name='Is Initial Stock'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='original_batch_number',
            field=models.CharField(blank=True, help_text='The original batch number before transfer', max_length=100, verbose_name='Original Batch Number'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='original_stock_entry',
            field=models.ForeignKey(blank=True, help_text='The original stock entry this was transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_entries', to='stock.stockentry', verbose_name='Original Stock Entry'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='source_transfer',
            field=models.ForeignKey(blank=True, help_text='The transfer that created this stock entry (if from transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_stock_entries', to='stock.stocktransfer', verbose_name='Source Transfer'),
        ),
    ]
