# Generated by Django 5.2.8 on 2025-11-23 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        ('stock', '0006_branchstock_is_initial_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price Per Unit'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='StockEntryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Group Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_entry_groups', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entry_groups', to='organization.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Entry Group',
                'verbose_name_plural': 'Stock Entry Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockentry',
            name='entry_group',
            field=models.ForeignKey(blank=True, help_text='Group this entry belongs to (for multi-product entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='stock.stockentrygroup', verbose_name='Entry Group'),
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Price Per Unit')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Batch Number')),
                ('notes', models.TextField(blank=True, verbose_name='Item Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='products.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items', to='stock.supplier', verbose_name='Supplier')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stocktransfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Stock Transfer Item',
                'verbose_name_plural': 'Stock Transfer Items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['transfer', 'product'], name='stock_stock_transfe_a6e5c9_idx'), models.Index(fields=['product', 'transfer'], name='stock_stock_product_7ae489_idx')],
            },
        ),
    ]
