# Generated by Django 5.2.8 on 2025-11-28 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stocktransfer_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='corrected_adjustment',
            field=models.ForeignKey(blank=True, help_text='The adjustment that was corrected by this adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_adjustments', to='stock.stockadjustment', verbose_name='Corrected Adjustment'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal'), ('correction', 'Correction'), ('damaged', 'Damaged')], max_length=20),
        ),
    ]
