# Generated by Django 5.2.8 on 2025-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stockadjustment_corrected_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Selling Price Per Unit'),
            preserve_default=False,
        ),
    ]
