# Generated by Django 5.2.8 on 2025-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_stockentry_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Purchase Price Per Unit'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='purchase_price',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Purchase Price Per Unit'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Purchase Price Per Unit'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Purchase Price Per Unit'),
        ),
    ]
