# Generated by Django 5.2.8 on 2025-11-23 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-is_main', 'name'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Mark this warehouse as the main warehouse. Only one warehouse should be main.', verbose_name='Is Main Warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organization.warehouse', verbose_name='Warehouse'),
        ),
    ]
