# Generated by Django 5.2.8 on 2025-12-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_branch_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='warehouse',
        ),
    ]
