# Generated by Django 5.2.8 on 2025-12-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_branch_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse this branch belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='organization.warehouse', verbose_name='Warehouse'),
        ),
    ]
