# Generated by Django 5.2.8 on 2026-03-22 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layby_number', models.CharField(max_length=50, unique=True, verbose_name='Layby Number')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laybys', to='organization.branch')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laybys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Layby',
                'verbose_name_plural': 'Laybys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaybyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('layby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='layby.layby')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layby_items', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='LaybyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('usd_cash', 'USD Cash'), ('zig_cash', 'ZIG Cash'), ('ecocash_usd', 'Ecocash USD'), ('ecocash_zig', 'Ecocash ZIG'), ('bank_transfer_zig', 'Bank Transfer ZIG'), ('bank_transfer_usd', 'Bank Transfer USD')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layby_payments', to=settings.AUTH_USER_MODEL)),
                ('layby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='layby.layby')),
            ],
        ),
    ]
