"""
Django settings for wealthbag project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-20ppk!m^6g4nc1a_rtq2+i0&#g7i^!19)lh1t&+tn5l!p1=_%d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'organization',
    'products',
    'sales',
    'stock',
    'accounting',
    'layby',

    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wealthbag.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wealthbag.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'decormasters',
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True


AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.JSONParser',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=360),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
} 

MAILJET_API_KEY = '154736a11ae0e7a65f7f8af98138d23d'
MAILJET_API_SECRET = '18d280e80fda3848f110ef04bb4fbe72'
DEFAULT_FROM_EMAIL = 'info@homehive.co.zw'
COMPANY_NAME = 'Decor Masters'
COMPANY_TIME_ZONE = 'Africa/Harare'
COMPANY_LOGO_URL = os.getenv(
    'COMPANY_LOGO_URL',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATcAAACiCAMAAAATIHpEAAABKVBMVEUAAAD///+MSpc5tI7xtw7aDBY6OjpAQECQkJBOTk68vLwvLy+4uLjn5+ciIiJkZGTv7+99fX2wsLCdnZ3Ozs74vA74+PjZ2dns7Ow0NDTg4ODa2topKSnhDBchISFvb2+oqKgYGBh4eHiISJPPz8+EhIRSUlKampqDBw03r4oRERFeXl5GRkYRCRMmFCmKaQh1BgxHBAfMCxUnfGLeqQ1XLl5+Q4hGJUzCkwszJgMzGzdoN3CxhgpwVQYSDgENKyIgZVCiCRDDCxQxmnkriWyTCA8XRzgIGRQcWEU1KAN0Pn1WQQVeMmZ+YAiUcAhFNQTMmwwbDh1PPAVLJ1EiGgKkfQq4iwpkTAZeBQkmAQQvAwUjbVYLJB1OBQgEDQp4BgwSOi4bAQM9BAZ5ubOBAAANaUlEQVR4nO2cCVvTShfHE7qSNnShJG0pXaCl0KIoi7hcZBPl9SquV3G5XvX7f4g3e85k1gJtcm/yfx6fR5NDMvPLnDlnzoxIUqJEiRIlShQhPdp+uLdkae/h9v/odnf3X67NWXrw5ODO7NoXTf35Kb20lHZk/O3hZ7Ldwcs5RE/uzrad0dIjg1oakUGOMOYeB6gZWnsV3zH3eS9AzSK3dxi0+7CGYTPd9XEYbY6AXuPQbG2jdq9I1MwhF09w24TB5gy5S2j3hILNUBzBHdKomeBe+3a00RZTcG8Y2Ay9ce0OWNjmHsQuOLyleqk14N46Zu8eMLnNvQq1E7PXIRObAc4JqvtsbLHz1LdsbOn026em2TtiBgL1JOyezFRvOMPNGHDWwuEDD9vcXKxmuL/43P4w7Tizm6kPYfdlltrjYUun956KuGm8HPUjH1s6/Z6XhDgKuzMz1Huum9oRlRtNY8aNl4VY3F5z1gquYlRRoi9NAbdt5tLUV4wyOCFulwm3oF7f5niLkZ9+FpzfhOJCjBLfR3xs6fSfQsuFWMXTpyJ570dJuiuQ974MuzOz1B/8ddZD005gnbUfdl9mKf4EZxeSBCa4GIUFSWCBarqpiKPGyk35GdySs6fFzURilL1Z4gy4vae2GW/AxWy4GTMce7h5xx3YqchavGY3U5cMT136y7fDjzgAHYTX/tBEz0WWPkE7Ri4SqxzEEw3c0qen0OwOdcTFE5vhqlwntXSHHFTXYrWzgIhwIGlpj3ACjnQg6WX8QgLQ670lgG5pae+SbPcqQO5BHCMCosNPe2n7nGp679PhU5rZnQ8v3QCx9uBV3LJdoj6+Ody+vNw+fP+Rbffu8cH+/v6Hg7sxqrglSpTo362ji+PdZ892jy+O2Ha/rzbOT07O7119mU27Iq2j47PNlKPNs29UdPfPTzOZzIqhTGbn9F7M0R3tetAcdLtEcr9PMgYvXys7G79m3dYI6SJAzSJ3jNttoNQscqdXM29uVLSLUzP1LGD25RSjZpHbCKXR4euMjC2VOnsBzb7uELEZ4E7CanmoomIzwAGzXztkaia489AaH54oToq5KtlJHXD/hNf+kHTBwpZKXbh25wxshu6H2YcwRIikUJvOFHefSc2IquH2Yub6xsaWSu3adifs4ZbJxCwb4WFLbX43zf7mUMtk4jXgOLObN8NxZrfYzXDP+NysXISeg3gzXJxykR+cqOA6KicqxM5Rj/jYUqnnkvQP300zK2F3ZoZ6LsLtQmh6y6zEqKQkEBZSqWOBLMTk9jvs3sxOxyLcvgly+zvs3sxOt8otRomIqJ8KzW8x8tOfItyMuLCRxFNELwSwbf6UpCs+tkwm7M7MUmd8buZ64YvAeiFWRV9m0dKWVRA55XO7F3ZfZqnvfG7PTbt7/Aku7K7MVlxHtbcYuI4aq2W9JLDSem7bcSNqjLIQS5xKkrsx84s9w8VvD/U7s5S06e2gMiu+K6fxO+3A9NTnvh0rNOzEzUtNMRZbx9DunM4tRktTIOqIu0DtKLFhZSee2CTp6Iw4t/0M2l2RTojEcW5z9eMbFh02dwl2X06CB7lWdmK1TsAUODhIOTYoSfdPdlY8dCuZ040YVcfJenGxe7Zp6Wz34jvd7uu9k50dY/mws3N6fhVfF0X04+jnz6MXfLtfX3///jr95iRKlChRokSJEiVKlChRokSJEv37VVKKnhYm//FsV9XK/cHttyvqysu+CpP/dL3Wyc3nm83GFJoWad2I20ArSaNGT5K65TZ+t1dCRLC4sbIlisbr2Wm8z9eNuMklaawqy0NJqhXxu1syovXbaG5AizJdWrOWz03hnbZuwq1bk6SOIknNkrSg4VhyaD/mb6fBiPIyR/rqFN4afPOk3PSKzU3vGH/wARcFbrK8XJrCe2/GTTVQlNRBrWv8vapjt6PBTZaHU3jxjbgZ/imV9LGyaPxdqWG3o8JNXpzymyflpnQtP20ttySpjOdwkeEmV6b75km5jcsjqWOMM2PyHTR72O3ocNNuP67eKA+p1aSGERPGW1l5jN+NDjeZkCXd4psn5jbqN01evbyWJ9yNELdydppvnnydNRqqdb2p6sRYHyFutz/D3YybJC2UBhUKkShxU6b55utwY2jm3PTcvKX10mI/wA3PLm/xzf92bjCFXNeQW+o03/xf4iZtIeBI9Zpbe/N/ihtaK9FaU3xzaNzahUZrxH9gu1AImLG4IZ5axtNycY0WCoXCAv3NwtyMfhZa3JYIchsX+6qmlZu1PNOXSopet81AB1jceiq41eR3iqzCQKk1y5qm1Zs1peKPWiFuEPVWt6Yb/dTKql4rrrLySRK3al21tew8ebEMTKruj3pmNfvV7UU4ePx1Ooub1MRujdzHqmodVkm6/nUd2WTJL6N9kHX3q1G4Kf6TDHlDpbdYDzxIq3VphVwSN8X7p9W+ARr1ZNVZSHpmZWvjIh8wa7qfi8kNjjdnPQOuwCJJFbQAcMvDb+p1OM/gNkBMvVJHsJvuo5RVktOSuBXhP3uKHJSaRbmZ1fV2DTdr8bllQa+1rcm5ZfHX2tJbNG7ziJ3nPUWZKlJtkM2tIjV0woNqAW4dqdEkmCl8bhVwx13Xg0s8bltBz/K1SuHWRrxaH+FPx0TaQWVzq7ZJPExQCLd8SyWajbncQCfKbh0JGHO4NciuZUoLvrmAP8awcq92qA+S7U8wGbfl4JTrqIZy08l0nQHH4AY74bUOXGNz65G/lv8aArcKYuWVOigdsEUov3G40WR9J3ziC6rM5jaGc4DvDOAimxurAR0ytxwyQr2JizncZFJB9XrcrE/A5yY3cG71riMFBsIy8AVwmcmN1Vk7hca5IeNKIT3bzD6KRUUHrSOlrGLctOBE0iFyw8zWcW4kaQr8pOAGk1vAt7S+Uq0qfbu/9qjGuCF8mn6CDB9VtD72qLE+rNnP0gjYRLhpSmd+voLG1VWcW7nYmV8foBNiSYSbNkQdAdxiceuQH5Id6LI7WQa5rSI/4ae0IxCWYTGr0TGdonw9bn0nf0UwVTBuCslMjFstj5z4AbdY3JAXqXBNVClrDRK3LOIOoLrcAk7ZRfm0Kvr1xpvfdBi9MG7e3gX8dmLcTNXAkCO+HOcGf1xFp6CWM+EHuCG+UAX2BcANLzoTj3HxuIFcGbYiyA1s+XTBZWFu8DuDiwxuiJuSMgWMGzK5LUO7HvzWYhvgHG5wJTgGdgFucAooAbMJuMl997tS+hDgBit3tI0J+GZ0cgvsnSGJYDO/davc4MKOwW0dmE3CTW4WJuEGR3tHgFsXpj1aYG8vsMrS9O6YU0PlcQM/LsgNmhG4LY+dU4OVYXBfpjYJN+Ba1Po69YsFV+ol3EQtjllV2plzg+usbIDccAJuwKpP6xyNG+7XwU9ov4Yx1YXKDUsVR9fiVpUoonAj7DcWSFU8Q13amAuZGzoj2wMO/JvOrUexEuFGrG9QKlKEI1yR4BbYlBbm1qJYiXBTSQXcFm25rRD3aMLmto7ctAoBFCIotwLFSoQbxbE7lGIS8RhB2Nxy6MQyFuXWplgJcZMpx4kr5HIjCXPY3LIot1VRbiNOvzBuyLZRnbY/ul4klZAJu6Nhcwv46UCUG7TCTy0TuKGVXsbRp3ER81eCddjc0E25CbiBcUodPej6FNn6oi0xTPXmq2iYV/GlfdjcAt9W2E8RCrTNYZQbMpVyzlT0OjAT1vDMJVp5r3hcQMouXSFuaEO4hxShNR55QuWGb87mUG6gcyPgOiY3OF2VMT8akbihqynoqcRVPPgyeOSZObfmasXSYFjFt7StkzXwgrfLjpTITG4wEQk6f6NJPucAkz5/79TqShf3W1DhiwA3popBbu5++iqSrljVLR37QVd5d6mP7csgTQGwzcmyWAqsRUHIwk86RIvbepCbMTwbhWwlcArE4oZG4r4bGwoDM9TYpSXOPqC/9LQv16sd4PA931bDo2+kuNkrmsDFch2rVVjceuhKXOsvVjqrQ8W5Stl3hjVrMC16c2e5362sNwqtQq4CEKv44blIcbO3CeiHPrxWLXCfWyRzQ8Kw76louqYZnwppRBTyXoacaE87mgVaZVfvKYdXLNUp3NAzJc5e4AKl+uaKsJyNEDc3aA3JtzW/xw63HGtkzpO5oZ4q293LsrmR6snR4ebllgvk+0N/E8DdLSJsC/jmFG7oHoztqfPsqeEa52pmxq0OQlaXZDAE/9nB22WrkCxt6TRubSSe5Hn8ScE0MtzKXSRhxxNizcgZ/MOJ/u5kh3bgsj6mcUN3rK3DsVnSoVK3aeQKQBS49QeBZc5CcMZfnkdwgl3dArm8XaSc47KEBB4791mlkVMov6yG9PtDIBDQI1gqG6Cvh0dPoJn1rei/P0RT9VqX+LteEFdVnbDnH2CHnOcxcuWqsxsPIwzofxuZzroOiCpeJtdq1J370VYWKGctNQo5/wo09S/nekJmW9ZXbwM7KOb/Sil0l+3eNRUvC1jwHoTatlaVZTci1vWqv1/cJrdQaoHrOX/Wz1UUXdW8BxU71/hdVOFrVMgZaoj936NRK5uzzG/a1bb11lt4UKJEicLS/wHH0VxbmxnDBQAAAABJRU5ErkJggg=='
)
SUPPORT_EMAIL = 'support@decormasters.com'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (User uploaded files like barcode images)
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
