# Generated by Django 5.2.8 on 2025-12-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('auditor', 'Auditor'), ('branch_manager', 'Branch Manager'), ('warehouse_manager', 'Warehouse Manager'), ('cashier', 'Cashier')], default='owner', max_length=20, verbose_name='Role'),
        ),
    ]
