# Generated by Django 5.2.8 on 2026-02-24 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='organization.warehouse'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.expensecategory'),
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_loss_reports', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_loss_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'incurred_on'], name='accounting__branch__57b575_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['warehouse', 'incurred_on'], name='accounting__warehou_826589_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlossreport',
            index=models.Index(fields=['start_date', 'end_date'], name='accounting__start_d_e15904_idx'),
        ),
    ]
