# Generated by Django 5.2.8 on 2025-11-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='accounting__branch__57b575_idx',
            old_name='accounting_branch__bbd079_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='accounting__warehou_826589_idx',
            old_name='accounting_warehous_5acdd3_idx',
        ),
        migrations.RenameIndex(
            model_name='profitlossreport',
            new_name='accounting__start_d_e15904_idx',
            old_name='accounting_start_d_90c175_idx',
        ),
    ]
