# Generated by Django 5.2.8 on 2026-03-22 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Rate')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True, verbose_name='Report Date')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total Sales Count')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Discount')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Tax')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Cost')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Profit')),
                ('total_items_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Items Sold')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit Margin (%)')),
                ('branch_summaries', models.JSONField(default=list, verbose_name='Branch Summaries')),
                ('payment_methods', models.JSONField(default=dict, verbose_name='Payment Methods Breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Daily Sales Report',
                'verbose_name_plural': 'Daily Sales Reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='sales_daily_report__524f16_idx'), models.Index(fields=['-report_date'], name='sales_daily_report__3cc82c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Sync ID')),
                ('sale_number', models.CharField(max_length=50, unique=True, verbose_name='Sale Number')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_of_payment', models.CharField(choices=[('usd_cash', 'USD Cash'), ('zig_cash', 'ZIG Cash'), ('ecocash_usd', 'Ecocash USD'), ('ecocash_zig', 'Ecocash ZIG'), ('bank_transfer_zig', 'Bank Transfer ZIG'), ('bank_transfer_usd', 'Bank Transfer USD')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='organization.branch')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Price Per Unit')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Purchase Price Per Unit (at time of sale)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when cash was received', verbose_name='Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of cash received from the cashier', max_digits=12, verbose_name='Total Cash Received')),
                ('type_of_payment', models.CharField(choices=[('usd_cash', 'USD Cash'), ('zig_cash', 'ZIG Cash'), ('ecocash_usd', 'Ecocash USD'), ('ecocash_zig', 'Ecocash ZIG'), ('bank_transfer_zig', 'Bank Transfer ZIG'), ('bank_transfer_usd', 'Bank Transfer USD')], default='usd_cash', help_text='Currency and payment method for the cash received', max_length=20, verbose_name='Type of Payment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the cash received', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Branch where cash was received', on_delete=django.db.models.deletion.CASCADE, related_name='cash_received_entries', to='organization.branch', verbose_name='Branch')),
                ('cashier', models.ForeignKey(help_text='Cashier who received the cash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_received', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
                ('entered_by', models.ForeignKey(help_text='Manager who entered this cash received record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_cash_received', to=settings.AUTH_USER_MODEL, verbose_name='Entered By')),
            ],
            options={
                'verbose_name': 'Cash Received',
                'verbose_name_plural': 'Cash Received',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['cashier', 'date'], name='sales_cashr_cashier_73a0ab_idx'), models.Index(fields=['branch', 'date'], name='sales_cashr_branch__7bb4ca_idx'), models.Index(fields=['date'], name='sales_cashr_date_963354_idx'), models.Index(fields=['cashier', 'branch', 'date', 'type_of_payment'], name='sales_cashr_cashier_2ecc29_idx')],
                'unique_together': {('cashier', 'branch', 'date', 'type_of_payment')},
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Discount Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Discount Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=12, verbose_name='Discount Value')),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('product', 'Specific Product'), ('category', 'Product Category'), ('branch', 'Specific Branch'), ('min_purchase', 'Minimum Purchase Amount')], default='all', max_length=20, verbose_name='Apply To')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total amount required for discount', max_digits=12, null=True, verbose_name='Minimum Purchase Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=12, null=True, verbose_name='Maximum Discount Amount')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times this discount can be used', null=True, verbose_name='Usage Limit')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organization.branch', verbose_name='Branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='sales_disco_code_2c2e54_idx'), models.Index(fields=['is_active', 'start_date', 'end_date'], name='sales_disco_is_acti_ae84b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReturnAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_authorization_codes', to='organization.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_return_authorization_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'is_active', 'expires_at'], name='sales_retur_branch__eb6257_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'created_at'], name='sales_sale_branch__7662c5_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'created_at'], name='sales_sale_status_23c89c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_sale_created_e208b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sync_id'], name='sales_sale_sync_id_5820d9_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sales_salei_sale_id_17278e_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product', 'sale'], name='sales_salei_product_be8a4f_idx'),
        ),
    ]
