# Generated by Django 5.2.8 on 2025-11-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_status_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='type_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'Ecocash'), ('one_money', 'One Money'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
