# Generated by Django 5.2.8 on 2025-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_type_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True, verbose_name='Report Date')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total Sales Count')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Discount')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Tax')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Cost')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Profit')),
                ('total_items_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Items Sold')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit Margin (%)')),
                ('branch_summaries', models.JSONField(default=list, verbose_name='Branch Summaries')),
                ('payment_methods', models.JSONField(default=dict, verbose_name='Payment Methods Breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Daily Sales Report',
                'verbose_name_plural': 'Daily Sales Reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='sales_daily_report__524f16_idx'), models.Index(fields=['-report_date'], name='sales_daily_report__3cc82c_idx')],
            },
        ),
    ]
