# Generated by Django 5.2.8 on 2025-11-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_dailysalesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sync_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Sync ID'),
        ),
    ]
