# Generated by Django 5.2.8 on 2025-11-28 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_branch_options_alter_warehouse_options_and_more'),
        ('sales', '0005_sale_sync_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sync_id'], name='sales_sale_sync_id_5820d9_idx'),
        ),
    ]
