# Generated by Django 5.2.8 on 2025-11-30 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_branch_options_alter_warehouse_options_and_more'),
        ('products', '0002_barcode'),
        ('sales', '0007_saleitem_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Discount Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Discount Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=12, verbose_name='Discount Value')),
                ('apply_to', models.CharField(choices=[('all', 'All Products'), ('product', 'Specific Product'), ('category', 'Product Category'), ('branch', 'Specific Branch'), ('min_purchase', 'Minimum Purchase Amount')], default='all', max_length=20, verbose_name='Apply To')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total amount required for discount', max_digits=12, null=True, verbose_name='Minimum Purchase Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=12, null=True, verbose_name='Maximum Discount Amount')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times this discount can be used', null=True, verbose_name='Usage Limit')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='organization.branch', verbose_name='Branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='sales_disco_code_2c2e54_idx'), models.Index(fields=['is_active', 'start_date', 'end_date'], name='sales_disco_is_acti_ae84b4_idx')],
            },
        ),
    ]
