# Generated by Django 5.2.8 on 2025-12-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_returnauthorizationcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='returnauthorizationcode',
            new_name='sales_retur_branch__eb6257_idx',
            old_name='sales_ret_branch__f99a68_idx',
        ),
    ]
