# Generated by Django 5.2.8 on 2025-12-03 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_branch_warehouse'),
        ('sales', '0010_rename_sales_ret_branch__f99a68_idx_sales_retur_branch__eb6257_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when cash was received', verbose_name='Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of cash received from the cashier', max_digits=12, verbose_name='Total Cash Received')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the cash received', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Branch where cash was received', on_delete=django.db.models.deletion.CASCADE, related_name='cash_received_entries', to='organization.branch', verbose_name='Branch')),
                ('cashier', models.ForeignKey(help_text='Cashier who received the cash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_received', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
                ('entered_by', models.ForeignKey(help_text='Manager who entered this cash received record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_cash_received', to=settings.AUTH_USER_MODEL, verbose_name='Entered By')),
            ],
            options={
                'verbose_name': 'Cash Received',
                'verbose_name_plural': 'Cash Received',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['cashier', 'date'], name='sales_cashr_cashier_73a0ab_idx'), models.Index(fields=['branch', 'date'], name='sales_cashr_branch__7bb4ca_idx'), models.Index(fields=['date'], name='sales_cashr_date_963354_idx')],
                'unique_together': {('cashier', 'branch', 'date')},
            },
        ),
    ]
