# Generated by Django 5.2.8 on 2025-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_cashreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Rate')),
            ],
        ),
    ]
