# Generated by Django 5.2.8 on 2025-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='type_of_payment',
            field=models.CharField(choices=[('usd_cash', 'USD Cash'), ('zig_cash', 'ZIG Cash'), ('ecocash_usd', 'Ecocash USD'), ('ecocash_zig', 'Ecocash ZIG'), ('bank_transfer_zig', 'Bank Transfer ZIG'), ('bank_transfer_usd', 'Bank Transfer USD')], default='cash', max_length=20),
        ),
    ]
