# Generated by Django 5.2.8 on 2025-12-14 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_branch_warehouse'),
        ('sales', '0013_alter_sale_type_of_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashreceived',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashreceived',
            name='type_of_payment',
            field=models.CharField(choices=[('usd_cash', 'USD Cash'), ('zig_cash', 'ZIG Cash'), ('ecocash_usd', 'Ecocash USD'), ('ecocash_zig', 'Ecocash ZIG'), ('bank_transfer_zig', 'Bank Transfer ZIG'), ('bank_transfer_usd', 'Bank Transfer USD')], default='usd_cash', help_text='Currency and payment method for the cash received', max_length=20, verbose_name='Type of Payment'),
        ),
        migrations.AlterUniqueTogether(
            name='cashreceived',
            unique_together={('cashier', 'branch', 'date', 'type_of_payment')},
        ),
        migrations.AddIndex(
            model_name='cashreceived',
            index=models.Index(fields=['cashier', 'branch', 'date', 'type_of_payment'], name='sales_cashr_cashier_2ecc29_idx'),
        ),
    ]
