# Generated by Django 5.2.8 on 2025-11-23 21:54

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_image', models.ImageField(blank=True, help_text='Auto-generated barcode image (CODE128 format)', null=True, upload_to=products.models.barcode_image_upload_path, verbose_name='Barcode Image')),
                ('barcode', models.CharField(db_index=True, help_text='Barcode value (product SKU or ID)', max_length=128, unique=True, verbose_name='Barcode Value')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary for quick product lookup', verbose_name='Primary Barcode')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this barcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product')),
            ],
            options={
                'verbose_name': 'Barcode',
                'verbose_name_plural': 'Barcodes',
                'ordering': ['-is_primary', 'barcode'],
                'indexes': [models.Index(fields=['barcode'], name='products_ba_barcode_33d5c3_idx'), models.Index(fields=['product', 'is_primary'], name='products_ba_product_fa7e62_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_barcode_per_product')],
            },
        ),
    ]
